### ISSUE TITLE
Error 'register'

### ISSUE THREAD

**Issue by BatSwarm** [joshuaKnauber/layer_painter#5]
So I've been working with 2.93.4 and I am getting this message when I try to activate the addon..
Report: Error
Traceback (most recent call last):
File "C:Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 386, in enable mod.register()
File "C:Users\User1\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\layer_painter\__init__.py", line 43, in register handlers.register()
AttributeError: module 'layer_painter.handlers' has no attribute 'register'

What can I do? the addon won't start :)

**Comment by joshuaKnauber** [comment]
Have you removed the addon, restarted blender and tried again?

**Comment by BatSwarm** [comment]
Oh no I didnt try that, so sorry! With that it works again :)! Thank you very much and sorry again for the mild inconvenience.
